### ISSUE TITLE
Thanks for your contribution,but i have a querstion.....

### ISSUE THREAD

**Issue by fengzhou** [cobertura/cobertura#296]
if a case run failed.the ant can'n be build success. is that right?

**Comment by christ66** [comment]
@fengzhou Not true! You should be able to build successfully without any issues. Cobertura has `cobertura-instrument` and `cobertura-report` options available, so if the unit tests fail, then you can still perform the report operation. See https://github.com/cobertura/cobertura/wiki/Ant-Task-Reference#cobertura-instrument-task and https://github.com/cobertura/cobertura/wiki/Ant-Task-Reference#cobertura-report-task for more information.

One thing you might need to do is setup the `JUNIT` task `haltonfailure` to `false` otherwise the ant task will halt when a failure happens.
